
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EY3lOakEwTWpFeU9Gb1hEVE14TURjeU5EQTBNakV5T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlMrCnJySWdoWiswRlNJdDkxNktWcXdxR283OFJzb2syUG5zcE5VbmNBbFJpbkRpeTJpQmJKQVVSVDhjOUc4dXA0aGEKU3h0WUNMK2NoSUdtOG1ZYnRsSE5LZ01CMWVtdHh5ZFZPTlY1U25mYjRBbG5xUURJWFJ1QVhQQXFscVRvT0NGTwpWT050ZGNCL0daTzhlL3JEQ0dQVEV5NHoxYW84UjRBUGttbkh6TDlQcUZVRklkUUxJSlNLOWpmQmdiSUx3L3hvCklzOWxrbXh3aTJGQi9sWkxlNnNqYmZNOHp0WGhqOGYreGJtZm41Vnp0eEM2RGlRTjI5RUVlU2NWTVpQQjE2Y1MKd1FhdU56eWNMSGxpMHdiOVpSb014WVAzKzhMYkhMUk9meitRSU1mVmRFSXpmd3FJOWtPUTdjY2l6RU1najBmZAp6TVFBbUdycThxcUI4S2pHRnNrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZFMndKQmlSUDk1Wm9QclJHcXIvbi9lMVVXQ1RNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCVi9EN2NxK0lEM3hiLzJ0U0tUZ2VBbStWMnc1dW5FQTlCU1ZpVDhDbGlDcG1kaVNWWQoxdm8zcjU0a2grTU9PVXhDMHlkWDJmR3Zlb2dnMEdMdm1XNjI5bE1SYXlhcnMvSjdLSURjUDMxUWZEbUtIR3pXCnVnbkJFTTZLMk91a0Z6enBab1F6RVRHL2N2YlluSGFkU1RmYU9UNUZaWWxwc2piZ2p6REhEOVRyU0F5bGNWSm0KbXd6ZzF0M2piNExBVHlXL3h6S2QrT3RMbEhsWTVieUE0UU41VDNiK1kvNTlvRGpxWFh2V3QvOG96MjFHbGJGVQpHK3IrSkFtaWZaUU5YMnMyZnk0WFlhUFBiaklkblhVck9qNlZQak92a0E0QkZibktndHNkSFlzNStVSnN2NkZ0CloxakVjL21IT1ZFTHRrdloySllObzBoUFRvRVA4UUN3VXBrVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://63100998-cd9f-4033-b4a7-a401aefc0a21.ap-south-1.linodelke.net:443
  name: lke32576

users:
- name: lke32576-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImdBYmFmY1NRUTFZLWxTZ1NNQUU3OWxYV2k1c003QWxxSzhaazlESTJWREUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tam1obGciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiODU5NDRhY2ItMGY2Yi00YjhhLTgxNDYtOGMxMTQ0MWM3ZWI1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.ywh47x-x6jVTSvXETiJMy38nGKno9Euoyo-yd0Biboo99yqEIk_QYnlUwN9_rykC9LASMaUzJEdeSYW1uk0q00C8Em2aBSf8GCo-_Mh-TeATTLYaZgHypEAvU8x6CE0aENPU3D2YIcuBtM9hJ-UIP2cYT-RQFDoSrUN-GtqH3Gt73zAGIWcWxb9KZrn6R2WiF-ExJUA2It5tUDF5UYT0qxV8tr9Z5Cj1wjoma6ztUaAsyrDA8540icTvNus4BSv0g2PARiY6hPA6UCePAKdjqZm3TvH8_YIWuW35kdwnbGfnGssaTgKoP1_wakUfESeXT9QY35ocSV4piTz5ZB8nyw

contexts:
- context:
    cluster: lke32576
    namespace: default
    user: lke32576-admin
  name: lke32576-ctx

current-context: lke32576-ctx
